basic_settings:
  site_title: Holy Terra - Marty Carcosa's Hobby Blog
  favicon_image: images/favicon.png

header_settings:
  logo_image: images/martycarcosa.svg
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Work'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'studies'
      url: 'studies'

footer_settings:
  logo_image: images/martycarcosa.svg
  logo_width: 100
  tagline: Holy Terra

hero_settings:
  background_image: images/backgrounds/holyterra-background.svg

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: 'mw at martinwright dot design'
  form_action: 'https://formspree.io/xyybywyz'
  confirmation_url: 'https://martinwright.design/thanks'
  email_subject: 'martinwright.design contact form'
  send_button_text: 'Get in Touch'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/martycarcosa?lang=en-GB'
  instagram_url: 'https://www.instagram.com/martycarcosa/?hl=en'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: 'whitesmoke'
  background_alt_color: '#212121'
  text_dark_color: '#212223'
  text_medium_color: '#6C7A89'
  text_light_color: '#AEB3BB'
  accent_color: '#FC3135'
  border_color: '#ECEDEF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,700;1,400&family=Pirata+One&display=swap" rel="stylesheet">'

  title_font: 'Pirata One, serif'
  body_font: 'Merriweather, serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: 0
  menu:
    small_size: 30
    medium_size: 16
    large_size: 18
    weight: 600
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 700
    letter_spacing: 0
    letter_spacing_small: 0
    line_height: 72
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 700
    letter_spacing: 0
    letter_spacing_small: 0
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 700
    letter_spacing: 0
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 22
    size_small: 22
    weight: 700
    letter_spacing: 0
    letter_spacing_small: 0
    line_height: 36
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 32
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0.4

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ".tag {background: rgba(0,0,0,0.05); padding: .3rem; margin-top: 1rem;}"
  header_js: ""
  footer_js: ''